/** Photo-inspired PicklyPH palette. Use semantic colors in app components. */
export const palette = {
  courtBlue: '#466E9E',
  courtGreen: '#4EA473',
  ballLime: '#E5FC35',
  deepNavy: '#14264D',
  white: '#FFFFFF',
  mist: '#F6F8FB',
  border: '#D8E1EC',
  mutedNavy: '#526078',
  strongGreen: '#246741',
  softGreen: '#EAF5EE',
  softBlue: '#EBF1F8',
  darkAmber: '#665800',
  softLime: '#F7FBCF',
  errorRed: '#B42318',
  softRed: '#FFF0EE',
} as const;

export const colors = {
  background: palette.mist,
  surface: palette.white,
  border: palette.border,
  text: palette.deepNavy,
  textSecondary: palette.mutedNavy,
  link: palette.courtBlue,
  primary: palette.courtBlue,
  onPrimary: palette.white,
  accent: palette.ballLime,
  onAccent: palette.deepNavy,
  secondary: palette.courtGreen,
  onSecondary: palette.deepNavy,
  selectedBackground: palette.softBlue,
  selectedText: palette.deepNavy,
  success: palette.strongGreen,
  successBackground: palette.softGreen,
  pending: palette.darkAmber,
  pendingBackground: palette.softLime,
  error: palette.errorRed,
  errorBackground: palette.softRed,
  mapCourtPin: palette.courtBlue,
  onMapCourtPin: palette.white,
  mapSessionPin: palette.strongGreen,
  onMapSessionPin: palette.white,
  mapSelectedPin: palette.ballLime,
  onMapSelectedPin: palette.deepNavy,
} as const;
