/** Concept C brand palette. Use semantic colors in app components. */
export const palette = {
  courtBlue: '#1E3F7C',
  courtGreen: '#2E9A4B',
  ballLime: '#D6F22E',
  deepGreen: '#1B7A3C',
  deepNavy: '#1E3F7C',
  ink: '#101820',
  white: '#FFFFFF',
  mist: '#F4F6FA',
  border: '#CFD9E8',
  mutedNavy: '#485468',
  strongGreen: '#1B7A3C',
  softGreen: '#EBF5EE',
  softBlue: '#EDF2FA',
  darkAmber: '#665800',
  softLime: '#F7FBCF',
  errorRed: '#B42318',
  softRed: '#FFF0EE',
  haze: '#C5D0E4',
  whiteVeil: 'rgba(255, 255, 255, 0.14)',
} as const;

export const colors = {
  background: palette.mist,
  surface: palette.white,
  border: palette.border,
  text: palette.deepNavy,
  textSecondary: palette.mutedNavy,
  link: palette.courtBlue,
  primary: palette.courtBlue,
  onPrimary: palette.white,
  /** 6.4:1 on primary; secondary text on navy surfaces. */
  onPrimaryMuted: palette.haze,
  /** Chips, dividers and court lines drawn over primary. */
  primaryOverlay: palette.whiteVeil,
  accent: palette.ballLime,
  onAccent: palette.deepNavy,
  secondary: palette.courtGreen,
  onSecondary: palette.ink,
  brandGreen: palette.deepGreen,
  selectedBackground: palette.softBlue,
  selectedText: palette.deepNavy,
  success: palette.strongGreen,
  successBackground: palette.softGreen,
  pending: palette.darkAmber,
  pendingBackground: palette.softLime,
  error: palette.errorRed,
  errorBackground: palette.softRed,
  mapCourtPin: palette.courtBlue,
  onMapCourtPin: palette.white,
  mapSessionPin: palette.strongGreen,
  onMapSessionPin: palette.white,
  mapSelectedPin: palette.ballLime,
  onMapSelectedPin: palette.deepNavy,
} as const;
